### ISSUE TITLE
Help  to use the last commit message as a name for a job

### ISSUE THREAD

**Issue by SabryTarek** [pay-justice/export-commit-message#1]
Want to use the last **commit message** as a name for a _job_ 
Thanks in advance @roboli

**Comment by roboli** [comment]
Hi @SabryTarek. Could you explain what you are trying to do please?

**Comment by SabryTarek** [comment]
> Hi @SabryTarek. Could you explain what you are trying to do please?

Hi @roboli I want to add my last git commit-message as a prefix for Circle CI pipeline name

I create this topic at circleci discuss
[discuss.circleci.com](https://discuss.circleci.com/t/how-to-add-my-last-git-commit-message-as-a-prefix-for-circle-ci-pipeline-name/42430)

**Comment by roboli** [comment]
Have you tried using double quotes @SabryTarek 

```
name: "$GIT_COMMIT_MESSAGE"
```

Are you sure this is possible? Seems name can't be set at runtime. Maybe trying using [parameters](https://circleci.com/docs/2.0/configuration-reference/#parameters)?

**Comment by SabryTarek** [comment]
I tried double quotes but it didn't work

and tried job parameters


```
version: 2.1
orbs:
  ecm: pay-justice/export-commit-message@0.0.1
jobs:
   build:
     parameters:
       commit-msg:
         type: env_var_name
         default: GIT_MSG # Note: replace with env var (without $) or remove it if the param is mandatory.
       AppName-msg:
         type: string
         default: 'my-app-name'
     docker:
       - image: ubuntu:latest
     steps:
       - checkout
       - ecm/export_commit
       - run: |
           echo "<< parameters.commit-msg >>  << parameters.AppName-msg >>"
workflows:
  workflow:
    jobs:
      - build:
          commit-msg: GIT_COMMIT_MESSAGE
          AppName-msg: $GIT_COMMIT_MESSAGE
```
the result is
https://ibb.co/QDt3nJC




**any suggestion?**
